- name: demo-01
  hosts: ios
  connection: local
  gather_facts: no
  tasks:
    - name: show version
      ios_command:
        commands: "show version"
      register: version
 
    - debug: var=version.stdout
 
    - name: show interface
      ios_command:
        commands: "show ip interface brief | inc up"
      register: interface
 
    - debug: var=interface.stdout_lines
