---
- name: sros demo
  hosts: sros
  connection: network_cli
  gather_facts: no
  tasks:
    - name: show version
      sros_command:
        commands:
          - show version
      register: command_output

    - debug: var=command_output
