- name: basic condition
  hosts: all
  connection: network_cli
  gather_facts: no
  tasks:
    - name: save
      cli_command:
        command: "{{ item }}"
        sendonly: yes
      loop:
        - save
        - y
      when: ansible_network_os=="ce"
