---
- name: Add several users
  hosts: ios
  connection: network_cli
  gather_facts: no
  vars:
    interfaces:
      - "interface": "ethernet0/1"
        "description": "yes"     
      - "interface" : "ethernet0/2"
        "description": "no"

  tasks: 
    - debug: var=item.interface
      with_items: "{{ interfaces }}"
    - debug: var=item.description
      with_items: "{{ interfaces }}"

