- name: Add several users
  hosts: ios
  connection: network_cli
  gather_facts: no
  tasks:
    - name: test loop
      ios_command:
        commands:
          - "show version"
          - "show ip interface br"
      register: commands_out

    - debug: var=commands_out
    - debug: var=commands_out.stdout[0]
    - debug: var=commands_out.stdout[1]
