- name: find user
  hosts: ios
  gather_facts: no
  connection: network_cli
  tasks:
    - name: find cli
      ios_command:
        commands: "show run | inc username"
      register: output

    - name: set_fact with filter(regex) 
      set_fact:
        users: "{{ output.stdout[0] | regex_findall(regexp) }}"
      vars:
        regexp: 'username (\S+)'
    - debug: var=users

    - name: make csv
      lineinfile:
        line: "{{ inventory_hostname }}, {{ item }}"
        path: user.csv
        create: yes
      loop: "{{ users }}"
