


- name: show interface by os
  include_tasks: "{{ ansible_network_os }}.yml"



- name: save output as text
  copy:
    content: "{{ interface_output.stdout[0] }}"
    dest: "{{ inventory_hostname }}_interface.txt"