


- name: get config based on ansible_network_os
  include_tasks: "{{ ansible_network_os }}.yml"

- debug: var=cfg_out.stdout

- name: create a textfile 
  copy:
    dest: "{{ inventory_hostname }}.cfg"
    content: "{{ cfg_out.stdout[0] }}"
  
