---

- name: include_tasks
  include_tasks: "{{ ansible_network_os }}.yml"
 
- name: copy configuration to textfile
  copy:
    dest: "{{ inventory_hostname }}_configuration.cfg"
    content: "{{ cfg_out.stdout[0] }}"


